- name: vTiger Installation
  hosts: localhost
  vars_files:
    - ../var/settings.yml

  tasks:
  - name: Apache | Configuration file /etc/php5/apache2/php.ini
    template: 
      src: ../templates/php.ini
      dest: /etc/php5/apache2/php.ini
      owner: root
      mode: 0755

  - name: Apache | Restart the Apache service
    service: 
      name: apache2 
      state: restarted

  - name: MySQL | Configuration file /root/.my.cnf
    template: 
      src: ../templates/root-my-cnf
      dest: /root/.my.cnf
      owner: root
      mode: 0600

  - name: MySQL | Restart the MySQL service
    service: 
      name: mysql 
      state: restarted

  - name: vTiger | Configuration file maestrano.json
    template: 
      src: ../templates/vtiger-maestrano.json
      dest: "{{ vtiger_root_path }}/maestrano.json"
      owner: www-data
      group: www-data
      mode: 777
