---

# php.ini
php_max_execution_time: '90'
php_memory_limit: '64M'
php_display_errors: 'On'
php_display_startup_errors: 'On'
php_html_errors: 'On'
php_post_max_size: '8M'
php_upload_max_filesize: '8M'

# my.cnf
innodb_additional_mem_pool_size: '16M'
innodb_buffer_pool_size: '64M'
mysql_max_allowed_packet: '16M'
mysql_character_set_server: 'utf8'
mysql_collation_server: 'utf8_general_ci'
innodb_file_per_table: 'innodb_file_per_table'

# mysql
mysql_root_password: 'password'

# vTiger installation
vtiger_db_user: vtiger6
vtiger_db_password: vtiger6
vtiger_db_name: vtiger6
vtiger_root_path: /var/lib/vtigercrm/webapp/

# vTiger default configuration
sso_enabled: "false"
connec_enabled: "false"
maestrano_environment: "production"
server_hostname: "server_hostname"
api_key: "api_key"
api_secret: "api_secret"